# Site settings
title: Xiong Shi Website
author:
  name: Xiong Shi
  email: shi.xiong@uni-konstanz.de

# Build settings
remote_theme: jekyll/minima

minima:
  skin: dark

header_pages:
  - home.md
  - research.md
  - publication.md
  - contact.md
