# Site settings
title: Great New Blog Title
author:
  name: Evan Will
  email: your-email@domain.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima

minima:
  skin: dark

header_pages:
  - home.md
  - research.md
  - publication.md
  - contact.md
